### ISSUE TITLE
Could you share how to build node as webassembly target using emscripten or some other tools.

### ISSUE THREAD

**Issue by liudonghua123** [Sandpack/nodebox-runtime#53]
Hi, I am just curious about how to build node as webassembly target. 

Could you share the patches and instructions on how to do it?

I want to execute some demonstration node code in browser without a server locally. codesandbox or webcontainer are good choices except they could not run self-hosted locally or offline.

I really want to learn how to make node run purely in browser.

**Comment by DeMoorJasper** [comment]
In essence it's almost all javascript, we didn't actually compile node to wasm that would be too big and slow.

Instead we use the native browser functionality and write a bunch of wrappers and polyfills to make it compatible with node, some sprinkles of wasm is used here and there to make it fast

**Comment by liudonghua123** [comment]
Thanks for your helpful information:😊
